// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogPostDocumentDataSlicesSlice = HeaderSlice | BlogBodySlice | SubHeaderSlice | BlogImageSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * SocialImage field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.socialimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  socialimage: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
  Simplify<BlogPostDocumentData>,
  'blog_post',
  Lang
>;

export type AllDocumentTypes = BlogPostDocument;

/**
 * Primary content in *BlogBody → Primary*
 */
export interface BlogBodySliceDefaultPrimary {
  /**
   * RichText field in *BlogBody → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_body.primary.richtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  richtext: prismic.RichTextField;
}

/**
 * Primary content in *BlogBody → Items*
 */
export interface BlogBodySliceDefaultItem {
  /**
   * rich text field in *BlogBody → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_body.items[].rich_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rich_text: prismic.RichTextField;
}

/**
 * Default variation for BlogBody Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogBodySliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<BlogBodySliceDefaultPrimary>,
  Simplify<BlogBodySliceDefaultItem>
>;

/**
 * Slice variation for *BlogBody*
 */
type BlogBodySliceVariation = BlogBodySliceDefault;

/**
 * BlogBody Shared Slice
 *
 * - **API ID**: `blog_body`
 * - **Description**: BlogBody
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogBodySlice = prismic.SharedSlice<'blog_body', BlogBodySliceVariation>;

/**
 * Primary content in *BlogImage → Primary*
 */
export interface BlogImageSliceDefaultPrimary {
  /**
   * BlogImage field in *BlogImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_image.primary.blogimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  blogimage: prismic.ImageField<never>;
}

/**
 * Default variation for BlogImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogImageSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<BlogImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogImage*
 */
type BlogImageSliceVariation = BlogImageSliceDefault;

/**
 * BlogImage Shared Slice
 *
 * - **API ID**: `blog_image`
 * - **Description**: BlogImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogImageSlice = prismic.SharedSlice<'blog_image', BlogImageSliceVariation>;

/**
 * Primary content in *Header → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * AuthorFullName field in *Header → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.primary.authorfullname
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  authorfullname: prismic.RichTextField;

  /**
   * Date field in *Header → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: header.primary.date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Header field in *Header → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.primary.header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header: prismic.RichTextField;

  /**
   * Image field in *Header → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * ReadTime field in *Header → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.primary.readtime
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  readtime: prismic.RichTextField;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<'default', Simplify<HeaderSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<'header', HeaderSliceVariation>;

/**
 * Primary content in *SubHeader → Primary*
 */
export interface SubHeaderSliceDefaultPrimary {
  /**
   * SubHeader field in *SubHeader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sub_header.primary.subheader
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheader: prismic.RichTextField;
}

/**
 * Default variation for SubHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubHeaderSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SubHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SubHeader*
 */
type SubHeaderSliceVariation = SubHeaderSliceDefault;

/**
 * SubHeader Shared Slice
 *
 * - **API ID**: `sub_header`
 * - **Description**: SubHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SubHeaderSlice = prismic.SharedSlice<'sub_header', SubHeaderSliceVariation>;

declare module '@prismicio/client' {
  interface CreateClient {
    (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogBodySlice,
      BlogBodySliceVariation,
      BlogBodySliceDefault,
      BlogImageSlice,
      BlogImageSliceVariation,
      BlogImageSliceDefault,
      HeaderSlice,
      HeaderSliceVariation,
      HeaderSliceDefault,
      SubHeaderSlice,
      SubHeaderSliceVariation,
      SubHeaderSliceDefault,
    };
  }
}
