// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  blog_body: dynamic(() => import('./BlogBody')),
  blog_image: dynamic(() => import('./BlogImage')),
  header: dynamic(() => import('./Header')),
  sub_header: dynamic(() => import('./SubHeader')),
};
