#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Linting to make sure your code is ✨ spotless ✨ which I'm sure it is..."
echo "If any linting errors are found, please fix them, git add ., and re-commit 🤠."
# yarn run lint:fix
