export const CONFIRM_CLAIM = 'CONFIRM_CLAIM';
export const CHECKING_WITHDRAWAL_ELIGIBILITY = 'CHECKING_WITHDRAWAL_ELIGIBILITY';
export const WITHDRAWAL_ELIGIBLE = 'WITHDRAWAL_ELIGIBLE';
export const WITHDRAWAL_INELIGIBLE = 'WITHDRAWAL_INELIGIBLE';
export const TRANSACTION_SUBMITTED = 'TRANSACTION_SUBMITTED';
export const TRANSACTION_CONFIRMED = 'TRANSACTION_CONFIRMED';
